---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/harikanew:dbimage   #here change repo shaikmustafa/harikanew with our dockerhub repo
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/harikanew:appimage   #here change repo shaikmustafa/harikanew with our dockerhub repo
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
